import { create } from 'zustand';
export const usePlayerStore = create((set) => ({
    currentMedia: null,
    isPlaying: false,
    currentTime: 0,
    duration: 0,
    volume: 1,
    isMuted: false,
    isFullscreen: false,
    quality: -1,
    qualities: [],
    setMedia: (media) => set({ currentMedia: media }),
    setPlaying: (isPlaying) => set({ isPlaying }),
    setCurrentTime: (currentTime) => set({ currentTime }),
    setDuration: (duration) => set({ duration }),
    setVolume: (volume) => set({ volume, isMuted: volume === 0 }),
    toggleMute: () => set((state) => ({ isMuted: !state.isMuted })),
    setFullscreen: (isFullscreen) => set({ isFullscreen }),
    setQuality: (quality) => set({ quality }),
    setQualities: (qualities) => set({ qualities }),
    reset: () => set({
        currentMedia: null,
        isPlaying: false,
        currentTime: 0,
        duration: 0,
        quality: -1,
        qualities: [],
    }),
}));
