import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Film, Play, Star } from 'lucide-react';
import { useVideoThumbnail } from '../../hooks/useVideoThumbnail.js';
export function MediaCard({ media, variant = 'portrait', showProgress = false, progress = 0, progressText }) {
    const thumbnail = useVideoThumbnail(media.id, media.m3u8Url, media.posterUrl);
    if (variant === 'landscape') {
        return (_jsxs(Link, { to: `/media/${media.id}`, className: "group block flex-shrink-0", children: [_jsxs("div", { className: "aspect-video bg-emby-bg-card rounded-md overflow-hidden relative", children: [thumbnail ? (_jsx("img", { src: thumbnail, alt: media.title, className: "w-full h-full object-cover group-hover:scale-105 transition-all duration-200", loading: "lazy" })) : (_jsx("div", { className: "w-full h-full bg-gradient-to-br from-emby-bg-elevated to-emby-bg-card flex items-center justify-center", children: _jsx(Film, { className: "w-10 h-10 text-emby-text-muted" }) })), _jsx("div", { className: "absolute inset-0 bg-black/0 group-hover:bg-black/50 transition-all duration-200 flex items-center justify-center", children: _jsx("div", { className: "opacity-0 group-hover:opacity-100 transition-opacity duration-200", children: _jsx("div", { className: "w-12 h-12 bg-emby-green/90 rounded-full flex items-center justify-center", children: _jsx(Play, { className: "w-6 h-6 text-white fill-white ml-0.5" }) }) }) }), showProgress && (_jsx("div", { className: "absolute bottom-0 left-0 right-0 h-1 bg-emby-border", children: _jsx("div", { className: "h-full bg-emby-green", style: { width: `${Math.min(100, progress)}%` } }) }))] }), _jsxs("div", { className: "pt-2 px-0.5", children: [_jsx("p", { className: "text-sm text-white truncate group-hover:text-emby-green-light transition-colors", children: media.title }), progressText && _jsx("p", { className: "text-xs text-emby-text-muted mt-0.5", children: progressText })] })] }));
    }
    // Portrait mode (default)
    return (_jsxs(Link, { to: `/media/${media.id}`, className: "group block", children: [_jsxs("div", { className: "aspect-[2/3] bg-emby-bg-card rounded-md overflow-hidden relative", children: [thumbnail ? (_jsx("img", { src: thumbnail, alt: media.title, className: "w-full h-full object-cover group-hover:scale-105 transition-all duration-200", loading: "lazy" })) : (_jsx("div", { className: "w-full h-full bg-gradient-to-br from-emby-bg-elevated to-emby-bg-card flex items-center justify-center", children: _jsx(Film, { className: "w-12 h-12 text-emby-text-muted" }) })), _jsx("div", { className: "absolute inset-0 bg-black/0 group-hover:bg-black/50 transition-all duration-200 flex items-center justify-center", children: _jsx("div", { className: "opacity-0 group-hover:opacity-100 transition-opacity duration-200", children: _jsx("div", { className: "w-12 h-12 bg-emby-green/90 rounded-full flex items-center justify-center", children: _jsx(Play, { className: "w-6 h-6 text-white fill-white ml-0.5" }) }) }) }), media.year && (_jsx("span", { className: "absolute bottom-2 left-2 bg-black/60 text-white text-xs px-2 py-0.5 rounded", children: media.year })), media.rating && (_jsxs("span", { className: "absolute bottom-2 right-2 bg-black/60 text-yellow-400 text-xs px-2 py-0.5 rounded font-medium flex items-center gap-0.5", children: [_jsx(Star, { className: "w-3 h-3 fill-yellow-400" }), media.rating.toFixed(1)] }))] }), _jsxs("div", { className: "pt-2 px-0.5", children: [_jsx("h3", { className: "text-white font-medium text-sm truncate group-hover:text-emby-green-light transition-colors", children: media.title }), media.category && (_jsx("p", { className: "text-emby-text-muted text-xs mt-0.5", children: media.category.name }))] })] }));
}
